DROP DATABASE IF EXISTS db_examen;
CREATE DATABASE db_examen;
USE db_examen;


CREATE TABLE fotos (
    id INT AUTO_INCREMENT PRIMARY,
    url VARCHAR(255) NOT NULL, 
    title VARCHAR(100),
    description VARCHAR(300), 
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    likes INT NOT NULL DEFAULT 0,
    dislikes INT NOT NULL DEFAULT 0
)

